### PR TITLE
adding no-interaction argument

### PR DESCRIPTION
**Pull request by mikefromlig**
Hello,
As I need to launch ecoindex-cli from a php script, I added a new argument: 'no-interaction', that bypasses confirmations (the one from recursive argument and the one about the number of urls).
Please tell me if you think it could be interesting for you to integrate this code in your repository, and feel free to adapt/correct it.
All changes are in app.py 
Thanks,
Best,
michael

### CODE REVIEW

**Review by vvatelot — COMMENTED** [review]
Hello @mikefromlig thanks for this PR!
This seems great. But, is it possible to update the documentation and maybe add a little test ? :smile:

**Comment by mikefromlig** [comment]
Hello,
It's done :). I added new lines in the README and a new function in test_app.py.
Tell me if there's something wrong.

**Comment by vvatelot** [comment]
Thank you for your contribution! That is great!

**Comment by vvatelot** [comment]
Woops! There is an issue with linting. Can you use Black to fix it ? :thinking:

**Comment by mikefromlig** [comment]
I didn't know such a tool (ie. black) exist. 
I think I did the job. Please tell me.

Also, I did some tests with urls_file, and I saw that the app crashes when a url is bad.
I had a bad time to discover which one it is, till I decided to update your code, adding a try/except around the asyncio.run.

I put the peace of code below (from app.py), with an output example. 
Do you want me to commit it here ?
Capture d’écran 2021-11-04 à 14 49 30
Capture d’écran 2021-11-04 à 14 49 44

**Comment by vvatelot** [comment]
@mikefromlig yes, you did it right with black! Thanks!
I merged your PR and packaged it as v2.2.0 :)

For the issue with the bad urls, as it is another subject, could you open another issue? So we could gather more information

**Pull request merged**
